# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef9dcd71190fbe42d4ab0ef920cddae158441451e5792b79d4b53008746a2cc3b19b3a7617cbd8a79c41df3eac20a3ef77b6c425cc68877aaa22352c2710ba76

test:
  secret_key_base: 47ea84aa019759dc4ada7a53b2cba4d8e664b1395016997c99b8492e9a0f2b18eac8d0fb3df73d9abf401ae181c7b79d783187c5b0c810b8ca7f0749e435f927

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
